### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by cas8180** [liquid-editor/canva-clone-reactjs#1]
No code present

**Comment by duyank** [comment]
thank you for creating the issue

Currently, source code only sent to the buyer
You can check the details below

Liquid Editor provides 2 license for users.
- **Starter: $149**
- **Pro: $999**

***Starter license*** is limited advanced layers such as frame, SVG and Text Effect. But you can use starter license for website that just need basic  design editor.

***Pro license*** includes all advanced layers that will help end-users build amazing designs.

To get the source code you need to pay via Paypal https://paypal.me/liquideditor and send me the screenshot of the payment After verifying I will send you the corresponding source code

**Comment by cas8180** [comment]
Thats retarded, dont use github to try and advertise. Use it cause you want to share source with the community

**Comment by duyank** [comment]
some parts will be shared for free in the next few months :)
I need to see how community interest to this
